sudo mysql -u root <<EOF
SET GLOBAL validate_password.policy=LOW;
CREATE USER 'mosta' IDENTIFIED BY 'Mosta123!';
GRANT ALL PRIVILEGES ON test_db.* TO 'mosta';
GRANT ALL PRIVILEGES ON *.* TO 'mosta' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF

CREATE TABLE article (
id INT AUTO_INCREMENT PRIMARY KEY,
image VARCHAR(255),
title VARCHAR(255) NOT NULL,
description TEXT,
content TEXT,
views INT DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE article_category (
article_id INT NOT NULL,
category_id INT NOT NULL,
PRIMARY KEY (article_id, category_id),
FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE,
FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;